version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'docker'
      MYSQL_ROOT_PASSWORD: 'docker'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume: