
--changeset kavi:2
CREATE TABLE sample.person (
  id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  firstname varchar (50) NULL,
  lastname varchar (50) NOT NULL,
  state bpchar (2) NULL,
  username varchar (8) NULL,
  column1 varchar(8) NULL,
  column2 varchar NULL,
  CONSTRAINT person_pkey PRIMARY KEY (id)
);
--rollback DROP TABLE IF EXISTS person;