version: "3.8"
services:

  sql-server-db:
    container_name: sql-server-db
    image: microsoft/mssql-server-linux:2017-latest
    restart: always
    ports:
      - "1433:1433"
    expose:
      - '1433'
    environment:
      SA_PASSWORD: "dockersqlserver"
      ACCEPT_EULA: "Y"